redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
global:
  domain: argocd.tootechy.com
certificate:
  enabled: true
server:
  replicas: 1
  ingress:
    enabled: true 
    ingressClassName: nginx 
    tls: true  
service:
  type: LoadBalancer
  port: 80