name: cicd

on:
  push:
    paths:
      - src/**
    branches: 
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: oladejotunde60/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - name: ArgoCD Setup
        shell: bash
        run: | 
         curl -ksSL -o argocd https://argocd-server.argocd:8080/download/argocd-linux-amd64
         chmod +x argocd
         sudo mv ./argocd /usr/local/bin/argocd
         
      - name: ArgoCD App Sync
        shell: bash
        run: | 
         argocd login https://argocd-server.argocd:8080 \
         --grpc-web \
         --username admin \
         --insecure \
         --password ${{ secrets.ARGOCD_PASSWORD }} 
         argocd app sync python-app 
   